### PR TITLE
Assignment-2 Submission

### PR DESCRIPTION
**Pull request by Jai2501**
- Complete Tasks pertaining to Assignment 2

### CODE REVIEW

**Review by Linda124 — DISMISSED** [review]
Looks good to me!

**Review by Nanxi-Huang — APPROVED** [review]
great work👍

**Review by laihuiqi — APPROVED** [review]
LGTM, in the state for Asg 2!

**Review by Linda124 — APPROVED** [review]
Issue with buttons is resolved. Thank you!

**Pull request merged**
